name: Update LeetCode Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate LeetCode Stats
        uses: saurabhdaware/leetcode-stats-card@v1
        with:
          username: AneesCodeX
          theme: dark
          file: README.md
