name: LeetCode Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily at midnight
  workflow_dispatch:

jobs:
  update-leetcode-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update LeetCode Stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LEETCODE_USER_NAME: AneesCodeX
          SHOW_LEETCODE: "True"
